<img title="GitHub Octocat" src='./img/Octocat.jpg?raw=true' style='height: 60px; padding-right: 15px' alt="Octocat" align="left"> This notebook is part of a GitHub repository: https://github.com/pessini/avian-flu-wild-birds-ireland 
<br>MIT Licensed
<br>Author: Leandro Pessini

# <p style="font-size:100%; text-align:left; color:#444444;">Gathering Data</p>

## Ordnance Survey *Ireland* (OSi) - Ireland’s National Mapping Agency

<img title="Ordnance Survey Ireland (OSi)" src="img/Logo-Colour-298x100.jpeg" alt="Ireland’s National Mapping Agency" align="right" style='height:120px; padding: 15px'>The spacial data is provided by [**Ordnance Survey *Ireland* (OSi)**](https://www.osi.ie/) under [Creative Commons licence](https://creativecommons.org/licenses/by/4.0/legalcode).

Ordnance Survey Ireland has evolved from the Ordnance Survey Office which was established in 1824, later becoming a state body under the Ordnance Survey Ireland Act 2001. Under this Act, Ordnance Survey Ireland continued its mainstream public service function of creating and maintaining the definitive mapping records of the State and also assumed the commercial function assigned to it under the Act of developing its commercial business and sales revenues.

**Administrative Areas** dataset generated from the [**2019 OSi National Statutory Boundary dataset**](https://data-osi.opendata.arcgis.com/datasets/OSi::administrative-areas-osi-national-statutory-boundaries-/about).

Dataset License: https://creativecommons.org/licenses/by/4.0/

In [1]:
import geopandas as gpd
import json
from pathlib import Path

In [2]:
url_geoJSON = 'https://opendata.arcgis.com/datasets/0d5984f732c54246bd087768223c92eb_0.geojson'
admin_areas_json = 'data/Administrative_Areas_Ireland.json'

In [3]:
# GeoJSON API
admin_areas = gpd.read_file(url_geoJSON, driver='GeoJSON')

# Saving the data downloaded to a local json file
admin_areas.to_file(admin_areas_json, driver='GeoJSON')

In [4]:
admin_areas.head()

,ENGLISH,GAEILGE,CONTAE,COUNTY,PROVINCE,GUID,CENTROID_X,CENTROID_Y,AREA,CC_ID,OBJECTID,Shape__Area,Shape__Length,geometry
0,DUBLIN CITY COUNCIL,None,Baile Átha Cliath,DUBLIN,Leinster,2ae19629-1433-13a3-e055-000000000001,716469.75,735272.06,1.283502e+08,265011,1,1.283502e+08,101493.212412,"POLYGON ((-6.38258 53.33367, -6.38261 53.33370..."
1,CORK CITY COUNCIL,None,Corcaigh,CORK,Munster,2ae19629-1434-13a3-e055-000000000001,565833.13,571933.83,1.865976e+08,45511,2,1.865976e+08,80293.730785,"POLYGON ((-8.38436 51.90533, -8.38425 51.90529..."
2,GALWAY CITY COUNCIL,None,Gaillimh,GALWAY,Connacht,2ae19629-1435-13a3-e055-000000000001,530067.66,726500.52,5.069505e+07,65011,3,5.069505e+07,64020.725628,"MULTIPOLYGON (((-9.13605 53.26682, -9.13606 53..."
3,OFFALY COUNTY COUNCIL,None,Uíbh Fhailí,OFFALY,Leinster,2ae19629-1496-13a3-e055-000000000001,631261.72,709672.35,2.000025e+09,185001,4,2.000025e+09,389927.708615,"POLYGON ((-7.97902 53.33689, -7.97878 53.33684..."
4,WICKLOW COUNTY COUNCIL,None,Cill Mhantáin,WICKLOW,Leinster,2ae19629-149e-13a3-e055-000000000001,707784.79,690738.10,2.025161e+09,255001,5,2.025161e+09,320629.958733,"MULTIPOLYGON (((-6.14602 52.78372, -6.14607 52..."

## BirdWatch Ireland - Species & Habitat Conservation

<img title="BirdWatch Ireland" src="img/BWI_logo_03_80px@2x.webp" alt="BirdWatch Ireland" style='height:150px; padding: 15px' align = "right">**BirdWatch Ireland** is the largest independent conservation organisation in Ireland and their objective is the protection of wild birds and their habitats. They have been doing an incredible work protecting birds and biodiversity in Ireland. Check out their amazing work [here](https://birdwatchireland.ie/our-work/).

The data is collected using **Web Scraping** technique from BirdWatch Ireland's website. There is a [list of Ireland's birds](https://birdwatchireland.ie/irelands-birds-birdwatch-ireland/list-of-irelands-birds/) with detailed information on every species.

To create our dataset and merge with the data provided by the Department of Agriculture, Food and the Marine, the focus will be on the bird's image and common name.

In [5]:
#!pip3 install beautifulsoup4

In [2]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import urllib
from urllib import parse
from skimage import io
#from PIL import Image

**Note**: `scikit-image imread`: OpenCV represents images in BGR order, whereas scikit-image represents images in RGB order. To utilize OpenCV functions after downloading the image, there is a extra step which is to convert the image from RGB to BGR.

In [5]:
# div class birds-with-filters (Parent)
# page/2/
no_pages = 24

def get_data(pageNo):  
    headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    r = requests.get('https://birdwatchireland.ie/irelands-birds-birdwatch-ireland/list-of-irelands-birds/'+str(pageNo), headers=headers)#, proxies=proxies)
    content = r.content
    soup = BeautifulSoup(content)
    #print(soup)

    alls = []
    for d in soup.findAll('article', attrs={'class':'bird'}):
        
        # image
        image_div = d.find('div', attrs={'class':'bird-img'})
        img_html = image_div.find('img')

        # text
        bird_name = d.find('h3', attrs={'class':'title'})

        complementary_info = d.find('div', attrs={'class':'bird-info'})
        bird_info = complementary_info.find_all('p')
        irish_name = bird_info[0]
        scientific_name = bird_info[1]
        bird_family = bird_info[2]

        all1=[]

        if img_html is not None:
            str_image = img_html['data-src']

            # there is a URL on Page 20 with an accent 
            # Snow Goose - https://birdwatchireland.ie/app/uploads/2019/02/Snowy-Owl-08-with-kill-René-Bruun.jpg
            # for that reason it needs to parse.quote() ignoring : and /, otherwise it will throw an error

            image = io.imread(urllib.parse.quote(str_image, safe=':/'))
            all1.append(image)
        else:
            all1.append('0')

        if bird_name is not None:
            all1.append(bird_name.text) if bird_name.text != '' else all1.append(np.nan)
        else:    
            all1.append('0')

        if irish_name is not None:
            all1.append(irish_name.text) if irish_name.text != '' else all1.append(np.nan)
        else:
            all1.append('0')

        if scientific_name is not None:
            all1.append(scientific_name.text) if scientific_name.text != '' else all1.append(np.nan)
        else:
            all1.append('0')

        if bird_family is not None:
            all1.append(bird_family.text) if bird_family.text != '' else all1.append(np.nan)
        else:
            all1.append('0')

        alls.append(all1)    

    return alls

In [6]:
results = []
# for i in range(1, no_pages+1):
for i in range(1, no_pages+1):
    url_to_append = "page/{}/".format(i)
    results.append(get_data(url_to_append))
    print(url_to_append+': OK')
flatten = lambda l: [item for sublist in l for item in sublist]
df_birds = pd.DataFrame(flatten(results),columns=['Image','Bird_Name','Irish_Name','Scientific_Name','Bird_Family'])
df_birds.to_csv('./data/BirdWatchIreland.csv', index=False)

page/1/: OK
page/2/: OK
page/3/: OK
page/4/: OK
page/5/: OK
page/6/: OK
page/7/: OK
page/8/: OK
page/9/: OK
page/10/: OK
page/11/: OK
page/12/: OK
page/13/: OK
page/14/: OK
page/15/: OK
page/16/: OK
page/17/: OK
page/18/: OK
page/19/: OK
page/20/: OK
page/21/: OK
page/22/: OK
page/23/: OK
page/24/: OK

In [7]:
df_birds.head()

,Image,Bird_Name,Irish_Name,Scientific_Name,Bird_Family
0,"[[[193, 145, 9], [189, 141, 5], [185, 137, 1],...",Arctic Tern,Geabhróg artach,Sterna paradisaea,Terns
1,"[[[33, 72, 87], [35, 74, 89], [37, 76, 93], [4...",Balearic Shearwater,Cánóg Bhailéarach,Puffinus mauretanicus,Tubenoses
2,"[[[52, 64, 88], [55, 67, 91], [57, 69, 93], [5...",Bar-tailed Godwit,Guilbneach stríocearrach,Limosa lapponica,Waders
3,"[[[89, 78, 46], [88, 77, 45], [85, 74, 42], [8...",Barn Owl,Scréachóg reilige,Tyto alba,Owls
4,"[[[130, 112, 74], [129, 111, 73], [127, 109, 7...",Barnacle Goose,Gé ghiúrainn,Branta leucopsis,Geese

## H5N1 Wild Bird Species Identification

Dataset provided by Ireland's [Department of Agriculture, Food and the Marine](https://data.gov.ie/dataset/h5n1-wild-bird-species-identification) which contains the locations of bird species captured in Ireland from 1980 to 2020 and wild birds that are targeted for the H5N1 strain of avian flu.

In [56]:
wild_birds = pd.read_csv("./data/98696_58589762-e8f9-4bb0-9d39-09570efbad62.xls", encoding='latin-1')
birdwatch = pd.read_csv("./data/BirdWatchIreland.csv")
wild_birds.head()

,Scientific_Name,Common_Name,Date,Year,Month,Day,Time,Country,Country_State_County,State,County,Locality,Latitude,Longitude,Parent_Species,target_H5_HPAI
0,Acrocephalus scirpaceus,Eurasian Reed Warbler,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Acrocephalus scirpaceus,0
1,Acrocephalus scirpaceus,Eurasian Reed Warbler,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Acrocephalus scirpaceus,0
2,Limosa haemastica,Hudsonian Godwit,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Limosa haemastica,0
3,Limosa haemastica,Hudsonian Godwit,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Limosa haemastica,0
4,Limosa haemastica,Hudsonian Godwit,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Limosa haemastica,0

**JOIN** the two bird datasets to link image to the specie. Using Scientific Name as key column

In [58]:
bird_flu = wild_birds.join(birdwatch.set_index('Scientific_Name'), on='Scientific_Name', lsuffix='_original', rsuffix='_bwi')

In [59]:
bird_flu.head()

,Scientific_Name,Common_Name,Date,Year,Month,Day,Time,Country,Country_State_County,State,County,Locality,Latitude,Longitude,Parent_Species,target_H5_HPAI,Image,Bird_Name,Irish_Name,Bird_Family
0,Acrocephalus scirpaceus,Eurasian Reed Warbler,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Acrocephalus scirpaceus,0,[[[143 165 142]\n [144 166 143]\n [145 168 1...,Reed Warbler,Ceolaire giolcaí,Warblers
1,Acrocephalus scirpaceus,Eurasian Reed Warbler,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Acrocephalus scirpaceus,0,[[[143 165 142]\n [144 166 143]\n [145 168 1...,Reed Warbler,Ceolaire giolcaí,Warblers
2,Limosa haemastica,Hudsonian Godwit,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Limosa haemastica,0,NaN,NaN,NaN,NaN
3,Limosa haemastica,Hudsonian Godwit,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Limosa haemastica,0,NaN,NaN,NaN,NaN
4,Limosa haemastica,Hudsonian Godwit,15/09/2015,2015,9,15,1100,Ireland,IE-C-GY,Connaught,Galway,Inishmore (Inis Mór),53.1291,-9.7507,Limosa haemastica,0,NaN,NaN,NaN,NaN

In [60]:
# Selecting only infected birds
infected_birds = bird_flu[bird_flu['target_H5_HPAI'] == 1]
top_infected_species = infected_birds.groupby('Scientific_Name').size().sort_values(ascending=False)
top_infected_species

Scientific_Name
Chroicocephalus ridibundus    332
Cygnus olor                   273
Ardea cinerea                 259
Egretta garzetta              227
Larus marinus                 152
Anas platyrhynchos            144
Buteo buteo                   121
Aythya fuligula               119
Pica pica                     118
Cygnus cygnus                 105
Falco peregrinus               92
Tadorna tadorna                83
Tachybaptus ruficollis         78
Larus canus                    76
Branta bernicla                63
Somateria mollissima           44
Anser anser                    43
Anas acuta                     40
Aythya marila                  37
Anser brachyrhynchus           33
Podiceps cristatus             29
Anas crecca                    25
Turdus pilaris                 21
Branta canadensis              18
Aythya ferina                  18
Bucephala clangula             16
Mergus merganser               15
Haliaeetus albicilla            4
dtype: int64

In [62]:
infected_birds_new = top_infected_species.to_frame().join(birdwatch.set_index('Scientific_Name'), on='Scientific_Name', lsuffix='_original', rsuffix='_bwi')

In [63]:
infected_birds_new

,0,Image,Bird_Name,Irish_Name,Bird_Family
Scientific_Name,,,,,
Chroicocephalus ridibundus,332,NaN,NaN,NaN,NaN
Cygnus olor,273,[[[44 39 36]\n [36 31 27]\n [57 54 49]\n .....,Mute Swan,Eala bhalbh,Swans
Ardea cinerea,259,[[[199 208 215]\n [175 184 191]\n [165 174 1...,Grey Heron,Corr réisc,Grey Heron
Egretta garzetta,227,[[[137 159 180]\n [106 128 149]\n [108 130 1...,Little Egret,Éigrit bheag,Cormorants (Egrets)
Larus marinus,152,[[[118 145 164]\n [118 145 164]\n [118 145 1...,Great Black-backed Gull,Droimneach mór,White-headed gulls
Anas platyrhynchos,144,[[[119 154 192]\n [120 155 193]\n [122 157 1...,Mallard,Mallard,Ducks
Buteo buteo,121,[[[131 142 48]\n [134 145 51]\n [136 147 ...,Buzzard,Clamhán,Raptors
Aythya fuligula,119,[[[159 159 157]\n [159 159 157]\n [159 159 1...,Tufted Duck,Lacha bhadánach,Ducks
Pica pica,118,[[[151 134 106]\n [150 133 105]\n [149 132 1...,Magpie,Snag breac,Crows
Cygnus cygnus,105,[[[127 127 135]\n [128 128 136]\n [129 129 1...,Whooper Swan,Eala Ghlórach,Swans
Falco peregrinus,92,[[[ 7 11 0]\n [ 9 13 0]\n [ 8 15 ...,Peregrine,Fabhcún gorm,Raptors
Tadorna tadorna,83,[[[ 62 85 116]\n [ 61 84 115]\n [ 61 84 1...,Shelduck,Seil-lacha,Ducks
Tachybaptus ruficollis,78,[[[136 164 203]\n [108 136 175]\n [110 138 1...,Little Grebe,Spágaire tonn,Grebes
Larus canus,76,[[[ 55 60 89]\n [ 56 61 90]\n [ 56 61 ...,Common Gull,Faoileán bán,Gulls
Branta bernicla,63,NaN,NaN,NaN,NaN
Somateria mollissima,44,[[[ 32 36 45]\n [ 33 37 46]\n [ 34 38 ...,Eider,Éadar,Ducks
Anser anser,43,[[[62 51 49]\n [62 51 49]\n [63 52 50]\n .....,Greylag Goose,Gé Ghlas,Geese
Anas acuta,40,[[[102 91 59]\n [ 96 85 53]\n [ 91 81 ...,Pintail,Biorearrach,Ducks
Aythya marila,37,NaN,NaN,NaN,NaN
Anser brachyrhynchus,33,[[[140 117 101]\n [139 116 100]\n [138 115 ...,Pink-footed Goose,Gé ghobghearr,Geese
Podiceps cristatus,29,[[[195 193 194]\n [195 193 194]\n [195 193 1...,Great Crested Grebe,Foitheach mór,Grebes
Anas crecca,25,[[[204 208 217]\n [204 208 217]\n [204 208 2...,Teal,Praslacha,Ducks
Turdus pilaris,21,[[[ 61 70 43]\n [ 62 71 44]\n [ 62 70 ...,Fieldfare,Sacán,Thrushes
Branta canadensis,18,[[[179 178 183]\n [179 178 183]\n [179 178 1...,Canada Goose,Gé Cheanadach,Geese
Aythya ferina,18,[[[193 196 203]\n [193 196 203]\n [193 196 2...,Pochard,Póiseard cíordhearg,Ducks
Bucephala clangula,16,[[[159 169 171]\n [158 168 170]\n [158 168 1...,Goldeneye,Órshúileach,Ducks
Mergus merganser,15,[[[66 67 51]\n [69 70 54]\n [72 73 57]\n .....,Goosander,Síolta mhór,Ducks
Haliaeetus albicilla,4,[[[118 120 143]\n [118 120 143]\n [118 120 1...,White-tailed Eagle,Iolar mara,Raptors

There are **3 species** among those Infected Birds which do not have image. Something might be different on those two datasets. Let's investigate.

- Chroicocephalus ridibundus
- Branta bernicla
- Aythya marila

`Chroicocephalus ridibundus`: have the same Common Name Black-headed Gull on both dataset but in BirdWatch Ireland's the Scientific Name is Larus ridibundus. I will switch the Scientific name so that the Join can work.

---

`Branta bernicla`: There are three subspecies of Brant (or Brent) Goose.
- **Branta bernicla nigricans** — Black-bellied Brant of extreme north-east Siberia to north central Canada.
- **Branta bernicla bernicla** — Dark-bellied Brant of northern and central Siberia.
- **Branta bernicla hrota** — Pale-bellied Brant of Canada, Greenland, Svalbard and Franz Josef Land.


Brent Goose (Light-bellied) = Branta bernicla hrota = Brant (Atlantic)
Branta bernicla bernicla = Brant (Dark-bellied)

Source: https://www.waterfowl.org.uk/wildfowl/swans-geese-allies/brent-goose/

---

`Aythya marila`:

In [28]:
null_df_t

Scientific_Name
Chroicocephalus ridibundus        332
Motacilla alba                    257
Saxicola rubicola                 250
Morus bassanus                    162
Linaria cannabina                 122
                                 ...
Catharus ustulatus                  1
Catharus fuscescens                 1
Branta bernicla (Gray-bellied)      1
Saxicola maurus                     1
Phalaropus tricolor                 1
Length: 245, dtype: int64

---
<img title="GitHub Mark" src="./img/GitHub-Mark-64px.png?raw=true" style="height: 32px; padding-right: 15px" alt="GitHub Mark" align="left"> [GitHub repository](https://github.com/pessini/avian-flu-wild-birds-ireland) <br>Author: Leandro Pessini